/**
 * The agent-facing capability catalog.
 *
 * This is the payoff for shaping the artifact as a contract rather than a step
 * list: a saved capability is *already* a tool definition. Its inputs are a
 * JSON Schema, its outputs are a typed return shape, and its declared business
 * outcomes tell the calling agent what "no" looks like before it ever invokes.
 * Nothing here is generated by a model or maintained by hand — it is a
 * projection of the same YAML a human reviewed and approved.
 *
 * Two properties worth pointing at:
 *
 *   - **Arguments are validated before a browser starts.** A malformed member
 *     id costs milliseconds and returns a precise complaint, rather than three
 *     page loads and a checkpoint timeout.
 *
 *   - **Business outcomes are advertised, not discovered.** An agent reading
 *     this catalog can see that `MEMBER_NOT_FOUND` is a possible answer and plan
 *     for it. That is the difference between an agent that handles a missing
 *     member and one that retries a "failure" three times.
 *
 * Unapproved capabilities are listed but flagged: they can be invoked, and any
 * irreversible step in them will refuse to run unattended. Hiding drafts would
 * make the catalog lie about what exists.
 */

import { z } from 'zod';
import type { Capability } from './schema.js';
import type { CapabilityStore } from './store.js';
import type { AppProfile } from './app-profile.js';
import type { Policy } from '../policy/policy.js';
import { RunRecorder } from '../observability/evidence.js';
import { replay, validateInputs, CapabilityInputError } from '../replay/executor.js';
import type { ReplayResult } from '../replay/outcomes.js';
import type { EscalationSink } from '../escalation/broker.js';

export interface JsonSchema {
  type: 'object';
  properties: Record<string, Record<string, unknown>>;
  required: string[];
  additionalProperties: false;
}

export interface CapabilityCard {
  name: string;
  version: string;
  title: string;
  summary: string;
  product: string;
  approval: 'draft' | 'approved';
  /** True if any step changes the institution's records irreversibly. */
  hasIrreversibleStep: boolean;
  inputSchema: JsonSchema;
  outputSchema: JsonSchema;
  businessOutcomes: Array<{ code: string; meaning: string }>;
}

const TYPE_MAP: Record<string, string> = {
  string: 'string',
  number: 'number',
  boolean: 'boolean',
  money: 'number',
};

export function inputSchemaOf(capability: Capability): JsonSchema {
  const properties: Record<string, Record<string, unknown>> = {};
  const required: string[] = [];
  for (const i of capability.spec.inputs) {
    properties[i.name] = {
      type: TYPE_MAP[i.type] ?? 'string',
      description: i.description,
      ...(i.pattern ? { pattern: i.pattern } : {}),
      ...(i.example ? { examples: [i.example] } : {}),
    };
    if (i.required) required.push(i.name);
  }
  return { type: 'object', properties, required, additionalProperties: false };
}

export function outputSchemaOf(capability: Capability): JsonSchema {
  const properties: Record<string, Record<string, unknown>> = {};
  for (const o of capability.spec.outputs) {
    properties[o.name] = { type: TYPE_MAP[o.type] ?? 'string', description: o.description };
  }
  return {
    type: 'object',
    properties,
    required: capability.spec.outputs.map((o) => o.name),
    additionalProperties: false,
  };
}

export function cardOf(capability: Capability): CapabilityCard {
  return {
    name: capability.metadata.name,
    version: capability.metadata.version,
    title: capability.metadata.title,
    summary: capability.metadata.summary.trim(),
    product: capability.metadata.app.product,
    approval: capability.metadata.approval,
    hasIrreversibleStep: capability.spec.steps.some((s) => s.guard.risk === 'irreversible'),
    inputSchema: inputSchemaOf(capability),
    outputSchema: outputSchemaOf(capability),
    businessOutcomes: capability.spec.outcomes.business.map((b) => ({ code: b.code, meaning: b.meaning.trim() })),
  };
}

/* --------------------------------------------------------- tool surface */

/**
 * The catalog rendered as function-calling tool definitions, so an AI agent can
 * be handed the whole set and pick one by name.
 *
 * The description deliberately spells out the possible non-success answers. A
 * tool description is the only thing many agents read before choosing, and
 * "returns MEMBER_NOT_FOUND if no such member exists" prevents a whole class of
 * pointless retry loops.
 */
export function toolDefinitionsOf(capabilities: Capability[]): Array<{
  name: string;
  description: string;
  parameters: JsonSchema;
}> {
  return capabilities.map((c) => {
    const card = cardOf(c);
    const outcomes = card.businessOutcomes.map((b) => b.code).join(', ');
    const returns = c.spec.outputs.map((o) => `${o.name} (${o.type})`).join(', ') || 'no values';
    return {
      name: card.name,
      description:
        `${card.title}. ${card.summary} ` +
        `Returns: ${returns}. ` +
        (outcomes ? `May instead report one of these business outcomes, which are answers and not errors: ${outcomes}. ` : '') +
        (card.hasIrreversibleStep
          ? 'CONTAINS AN IRREVERSIBLE STEP: it will stop and ask a human unless explicitly authorised.'
          : 'Read-only: safe to call speculatively.'),
      parameters: card.inputSchema,
    };
  });
}

/* ------------------------------------------------------------- catalog */

export interface InvokeContext {
  tenantId: string;
  profile: AppProfile;
  policy: Policy;
  evidenceDir?: string;
  sink?: EscalationSink;
  authorizeIrreversible?: boolean;
  headful?: boolean;
}

export class Catalog {
  constructor(private readonly store: CapabilityStore) {}

  list(): CapabilityCard[] {
    return this.store.listLatest().map(cardOf);
  }

  describe(name: string): CapabilityCard {
    return cardOf(this.store.load(name));
  }

  tools(): ReturnType<typeof toolDefinitionsOf> {
    return toolDefinitionsOf(this.store.listLatest());
  }

  /**
   * Invoke a capability by name with typed arguments — the call an AI agent
   * makes in production.
   */
  async invoke(name: string, args: Record<string, unknown>, ctx: InvokeContext): Promise<ReplayResult> {
    const capability = this.store.load(name);

    // Fail fast, before anything expensive or side-effecting happens.
    validateInputs(capability, args);

    const recorder = new RunRecorder(
      `${name}-${Date.now().toString(36)}`,
      'replay',
      ctx.evidenceDir ?? 'evidence',
      { consoleEcho: false },
    );

    return replay({
      capability,
      params: args,
      tenantId: ctx.tenantId,
      profile: ctx.profile,
      policy: ctx.policy,
      recorder,
      ...(ctx.sink ? { sink: ctx.sink } : {}),
      ...(ctx.authorizeIrreversible !== undefined ? { authorizeIrreversible: ctx.authorizeIrreversible } : {}),
      ...(ctx.headful !== undefined ? { headful: ctx.headful } : {}),
    });
  }
}

/** Zod mirror of the invocation envelope, for callers that want to validate it. */
export const InvocationSchema = z.object({
  capability: z.string(),
  arguments: z.record(z.string(), z.unknown()),
  tenant: z.string().default('base'),
  authorizeIrreversible: z.boolean().default(false),
});

export { CapabilityInputError };
