/**
 * What every run left behind.
 *
 * Curated evidence (`evidence/<name>/`, regenerated by `npm run evidence`) is
 * separated from ad-hoc panel runs (`evidence/runs/`, gitignored) because they
 * are different kinds of artifact: one is a reviewed set of named scenarios
 * referenced from the write-up, the other is whatever someone clicked while
 * demonstrating. Mixing them would make a reviewer guess which was which.
 *
 * Each directory holds the structured event log, the result contract, the
 * human-readable summary, and screenshots plus DOM/accessibility snapshots at
 * the moments they were taken.
 */

import { useEffect, useState } from 'react';
import { api, type EvidenceRun } from '../lib/api';

export interface EvidenceProps {
  /** A directory to open on mount, e.g. from a verdict's "open" link. */
  openDir?: string | null;
  onOpened?: () => void;
}

const IMAGE = /\.png$/i;
const TEXTUAL = /\.(json|jsonl|md|txt|html)$/i;

export function Evidence({ openDir, onOpened }: EvidenceProps): JSX.Element {
  const [runs, setRuns] = useState<EvidenceRun[]>([]);
  const [selected, setSelected] = useState<string | null>(null);
  const [summary, setSummary] = useState<string>('');
  const [error, setError] = useState<string>('');

  const load = async (): Promise<void> => {
    try {
      const r = await api.evidence();
      setRuns(r.runs);
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    }
  };

  useEffect(() => {
    void load();
  }, []);

  useEffect(() => {
    if (!openDir) return;
    setSelected(openDir);
    onOpened?.();
    void load();
  }, [openDir]);

  useEffect(() => {
    if (!selected) {
      setSummary('');
      return;
    }
    let live = true;
    void fetch(api.evidenceFileUrl(`${selected}/summary.md`))
      .then((r) => (r.ok ? r.text() : ''))
      .then((t) => live && setSummary(t))
      .catch(() => live && setSummary(''));
    return () => {
      live = false;
    };
  }, [selected]);

  const current = runs.find((r) => r.dir === selected);
  const curated = runs.filter((r) => r.curated);
  const adhoc = runs.filter((r) => !r.curated);

  const statusClass = (s: string): string =>
    s === 'success' ? 'good' : s === 'business_outcome' ? 'warn' : s === 'failed' ? 'bad' : '';

  const list = (title: string, items: EvidenceRun[], note: string): JSX.Element => (
    <>
      <h3 className="sec">{title}</h3>
      <p className="hint">{note}</p>
      {items.length === 0 && <p className="hint">None yet.</p>}
      {items.map((r) => (
        <div
          key={r.dir}
          className={`card clickable${selected === r.dir ? ' sel' : ''}`}
          onClick={() => setSelected(r.dir)}
        >
          <h3>{r.dir}</h3>
          <div>
            <span className={`badge ${statusClass(r.status)}`}>{r.status}</span>
            {r.code && <span className="tag">{r.code}</span>}
            {r.tenant && <span className="tag">{r.tenant}</span>}
          </div>
          {r.capability && <p className="why">{r.capability}</p>}
        </div>
      ))}
    </>
  );

  return (
    <div>
      <h2>Evidence</h2>
      {error && <p className="hint">{error}</p>}

      <div className="grid2">
        <div>
          {current ? (
            <>
              <h3>{current.dir}</h3>
              <table className="kv">
                <tbody>
                  <tr>
                    <th>Status</th>
                    <td>
                      <span className={`badge ${statusClass(current.status)}`}>{current.status}</span>
                    </td>
                  </tr>
                  {current.capability && (
                    <tr>
                      <th>Capability</th>
                      <td className="mono">{current.capability}</td>
                    </tr>
                  )}
                  {current.startedAt && (
                    <tr>
                      <th>Started</th>
                      <td className="mono">{current.startedAt}</td>
                    </tr>
                  )}
                  {current.durationMs != null && (
                    <tr>
                      <th>Duration</th>
                      <td>{current.durationMs} ms</td>
                    </tr>
                  )}
                </tbody>
              </table>

              {summary && (
                <>
                  <h3 className="sec">Summary</h3>
                  <pre>{summary}</pre>
                </>
              )}

              <h3 className="sec">Files</h3>
              <ul>
                {(current.files ?? []).map((f) => (
                  <li key={f}>
                    <a
                      href={api.evidenceFileUrl(`${current.dir}/${f}`)}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="mono"
                    >
                      {f}
                    </a>
                    {TEXTUAL.test(f) && <span className="hint"> — structured log / snapshot</span>}
                  </li>
                ))}
              </ul>

              {(current.files ?? []).filter((f) => IMAGE.test(f)).length > 0 && (
                <>
                  <h3 className="sec">Screenshots</h3>
                  {(current.files ?? [])
                    .filter((f) => IMAGE.test(f))
                    .map((f) => (
                      <figure key={f} style={{ margin: '0 0 .8rem' }}>
                        <img className="shot" src={api.evidenceFileUrl(`${current.dir}/${f}`)} alt={f} />
                        <figcaption className="hint mono">{f}</figcaption>
                      </figure>
                    ))}
                </>
              )}
            </>
          ) : (
            <p className="hint">Choose a run.</p>
          )}
        </div>

        <div>
          {list('Curated', curated, 'A fixed, committed set regenerated by npm run evidence.')}
          {list('From this panel', adhoc, 'Real evidence in the same format, gitignored.')}
        </div>
      </div>
    </div>
  );
}
